export const commonPlatForms = [
    { id: 1, name: "Instagram", url: "instagram.com/", total_users: 2350000000 },
    { id: 2, name: "Twitter (X)", url: "twitter.com/", total_users: 556000000 },
    { id: 3, name: "Facebook", url: "facebook.com/", total_users: 3050000000 },
    { id: 4, name: "LinkedIn", url: "linkedin.com/in/", total_users: 1000000000 },
    { id: 5, name: "TikTok", url: "tiktok.com/@", total_users: 1700000000 },
    { id: 6, name: "Pinterest", url: "pinterest.com/", total_users: 482000000 },
    { id: 7, name: "Snapchat", url: "snapchat.com/add/", total_users: 414000000 },
    { id: 8, name: "Reddit", url: "reddit.com/user/", total_users: 430000000 },
    // { id: 9, name: "Tumblr", url: ".tumblr.com", total_users: 135000000 },
    { id: 10, name: "Mastodon", url: "mastodon.instance/@", total_users: 10000000 },
    { id: 11, name: "YouTube", url: "youtube.com/@", total_users: 2700000000 },
    { id: 12, name: "Medium", url: "medium.com/@", total_users: 100000000 },
    { id: 13, name: "Dev.to", url: "dev.to/", total_users: 10000000 },
    // { id: 14, name: "Substack", url: ".substack.com", total_users: 35000000 },
    // { id: 15, name: "WordPress", url: ".wordpress.com", total_users: 810000000 },
    // { id: 16, name: "Blogger", url: ".blogspot.com", total_users: 100000000 },
    { id: 17, name: "GitHub", url: "github.com/", total_users: 100000000 },
    { id: 18, name: "GitLab", url: "gitlab.com/", total_users: 30000000 },
    { id: 19, name: "Bitbucket", url: "bitbucket.org/", total_users: 10000000 },
    // { id: 20, name: "Stack Overflow", url: "stackoverflow.com/users/userid/", total_users: 20000000 },
    { id: 21, name: "Twitch", url: "twitch.tv/", total_users: 140000000 },
    { id: 22, name: "Steam Community", url: "steamcommunity.com/id/", total_users: 132000000 },
    // { id: 23, name: "Xbox Live", url: "xboxgamertag.com/profile/", total_users: 120000000 },
    // { id: 24, name: "PlayStation Network", url: "my.playstation.com/profile/", total_users: 120000000 },
    { id: 25, name: "Fiverr", url: "fiverr.com/", total_users: 4300000 },
    { id: 26, name: "Upwork", url: "upwork.com/freelancers/~", total_users: 18000000 },
    { id: 27, name: "Behance", url: "behance.net/", total_users: 30000000 },
    { id: 28, name: "Dribbble", url: "dribbble.com/", total_users: 17000000 },
    // { id: 29, name: "OpenSea", url: "opensea.io/collection/", total_users: 2500000 },
    // { id: 30, name: "Lens Protocol", url: "lenster.xyz/u/", total_users: 300000 },
    // { id: 31, name: "Nostr", url: ".nostr.build", total_users: 500000 }
  ];
  
export const ListOfPlatforms = [
    {
      id: 1,
      name: "Instagram",
      url: "instagram.com/",
      total_users: 2350000000,
    },
    {
      id: 2,
      name: "Twitter (X)",
      url: "twitter.com/",
      total_users: 556000000,
    },
    {
      id: 3,
      name: "Facebook",
      url: "facebook.com/",
      total_users: 3050000000,
    },
    {
      id: 4,
      name: "LinkedIn",
      url: "linkedin.com/in/",
      total_users: 1000000000,
    },
    {
      id: 5,
      name: "TikTok",
      url: "tiktok.com/@",
      total_users: 1700000000,
    },
    {
      id: 6,
      name: "Pinterest",
      url: "pinterest.com/",
      total_users: 482000000,
    },
    {
      id: 7,
      name: "Snapchat",
      url: "snapchat.com/add/",
      total_users: 414000000,
    },
    {
      id: 8,
      name: "Reddit",
      url: "reddit.com/user/",
      total_users: 430000000,
    },
    {
      id: 9,
      name: "Tumblr",
      url: ".tumblr.com",
      total_users: 135000000,
    },
    {
      id: 10,
      name: "Mastodon",
      url: "mastodon.instance/@",
      total_users: 10000000,
    },
    {
      id: 11,
      name: "YouTube",
      url: "youtube.com/@",
      total_users: 2700000000,
    },
    {
      id: 12,
      name: "Medium",
      url: "medium.com/@",
      total_users: 100000000,
    },
    { id: 13, name: "Dev.to", url: "dev.to/", total_users: 10000000 },
    {
      id: 14,
      name: "Substack",
      url: ".substack.com",
      total_users: 35000000,
    },
    {
      id: 15,
      name: "WordPress",
      url: ".wordpress.com",
      total_users: 810000000,
    },
    {
      id: 16,
      name: "Blogger",
      url: ".blogspot.com",
      total_users: 100000000,
    },
    {
      id: 17,
      name: "GitHub",
      url: "github.com/",
      total_users: 100000000,
    },
    {
      id: 18,
      name: "GitLab",
      url: "gitlab.com/",
      total_users: 30000000,
    },
    {
      id: 19,
      name: "Bitbucket",
      url: "bitbucket.org/",
      total_users: 10000000,
    },
    {
      id: 20,
      name: "Stack Overflow",
      url: "stackoverflow.com/users/userid/",
      total_users: 20000000,
    },
    {
      id: 21,
      name: "Twitch",
      url: "twitch.tv/",
      total_users: 140000000,
    },
    {
      id: 22,
      name: "Steam Community",
      url: "steamcommunity.com/id/",
      total_users: 132000000,
    },
    {
      id: 23,
      name: "Xbox Live",
      url: "xboxgamertag.com/profile/",
      total_users: 120000000,
    },
    {
      id: 24,
      name: "PlayStation Network",
      url: "my.playstation.com/profile/",
      total_users: 120000000,
    },
    {
      id: 25,
      name: "Fiverr",
      url: "fiverr.com/",
      total_users: 4300000,
    },
    {
      id: 26,
      name: "Upwork",
      url: "upwork.com/freelancers/~",
      total_users: 18000000,
    },
    {
      id: 27,
      name: "Behance",
      url: "behance.net/",
      total_users: 30000000,
    },
    {
      id: 28,
      name: "Dribbble",
      url: "dribbble.com/",
      total_users: 17000000,
    },
    {
      id: 29,
      name: "OpenSea",
      url: "opensea.io/",
      total_users: 2500000,
    },
    {
      id: 30,
      name: "Lens Protocol",
      url: "lenster.xyz/u/",
      total_users: 300000,
    },
    { id: 31, name: "Nostr", url: ".nostr.build", total_users: 500000 },
    {
      id: 32,
      name: "AngelList",
      url: "angel.co/",
      total_users: 10000000,
    },
    {
      id: 33,
      name: "Lemon8",
      url: "lemon8-app.com/@",
      total_users: 5000000,
    },
    { id: 34, name: "Ko-fi", url: "ko-fi.com/", total_users: 2000000 },
    {
      id: 35,
      name: "Patreon",
      url: "patreon.com/",
      total_users: 8000000,
    },
    {
      id: 36,
      name: "Buy Me a Coffee",
      url: "buymeacoffee.com/",
      total_users: 1000000,
    },
    {
      id: 37,
      name: "Kickstarter",
      url: "kickstarter.com/profile/",
      total_users: 5000000,
    },
    {
      id: 38,
      name: "IndieGoGo",
      url: "indiegogo.com/individuals/",
      total_users: 2000000,
    },
    {
      id: 39,
      name: "Rumble",
      url: "rumble.com/c/",
      total_users: 4000000,
    },
    {
      id: 40,
      name: "Odysee",
      url: "odysee.com/@",
      total_users: 3000000,
    },
    { id: 41, name: "Gab", url: "gab.com/", total_users: 4000000 },
    { id: 42, name: "Minds", url: "minds.com/", total_users: 2000000 },
    { id: 43, name: "Ello", url: "ello.co/", total_users: 1000000 },
    { id: 44, name: "Vero", url: "vero.co/", total_users: 500000 },
    {
      id: 45,
      name: "PeerTube",
      url: "instance.peertube.com/accounts/",
      total_users: 200000,
    },
    { id: 46, name: "MeWe", url: "mewe.com/i/", total_users: 2000000 },
    {
      id: 47,
      name: "Gettr",
      url: "gettr.com/user/",
      total_users: 4000000,
    },
    {
      id: 48,
      name: "Parler",
      url: "parler.com/profile/",
      total_users: 3000000,
    },
    {
      id: 49,
      name: "Eddie Bauer",
      url: "eddiebauer.com/",
      total_users: 10000000,
    },
    {
      id: 50,
      name: "FanCentro",
      url: "fancentro.com/",
      total_users: 2000000,
    },
    { id: 51, name: "Cameo", url: "cameo.com/", total_users: 1000000 },
    {
      id: 52,
      name: "Letterboxd",
      url: "letterboxd.com/",
      total_users: 3000000,
    },
    {
      id: 53,
      name: "Goodreads",
      url: "goodreads.com/user/show/",
      total_users: 9000000,
    },
    {
      id: 54,
      name: "Last.fm",
      url: "last.fm/user/",
      total_users: 3000000,
    },
    {
      id: 55,
      name: "Chess.com",
      url: "chess.com/member/",
      total_users: 15000000,
    },
    {
      id: 56,
      name: "Lichess",
      url: "lichess.org/@/",
      total_users: 5000000,
    },
    {
      id: 57,
      name: "Speedrun.com",
      url: "speedrun.com/user/",
      total_users: 2000000,
    },
    {
      id: 58,
      name: "Replit",
      url: "replit.com/@",
      total_users: 2000000,
    },
    {
      id: 59,
      name: "CodePen",
      url: "codepen.io/",
      total_users: 2000000,
    },
    {
      id: 60,
      name: "JSFiddle",
      url: "jsfiddle.net/user/",
      total_users: 1000000,
    },
    {
      id: 61,
      name: "Kaggle",
      url: "kaggle.com/",
      total_users: 7000000,
    },
    {
      id: 62,
      name: "Coursera",
      url: "coursera.org/user/",
      total_users: 9000000,
    },
    { id: 63, name: "EdX", url: "edx.org/user/", total_users: 4000000 },
    {
      id: 64,
      name: "SoloLearn",
      url: "sololearn.com/profile/",
      total_users: 3000000,
    },
    {
      id: 65,
      name: "Pluralsight",
      url: "pluralsight.com/profile/",
      total_users: 2000000,
    },
    {
      id: 66,
      name: "Duolingo",
      url: "duolingo.com/profile/",
      total_users: 6000000,
    },
    {
      id: 67,
      name: "HackerRank",
      url: "hackerrank.com/",
      total_users: 10000000,
    },
    {
      id: 68,
      name: "HackerEarth",
      url: "hackerearth.com/@",
      total_users: 4000000,
    },
    {
      id: 69,
      name: "LeetCode",
      url: "leetcode.com/",
      total_users: 6000000,
    },
    {
      id: 70,
      name: "CodeWars",
      url: "codewars.com/users/",
      total_users: 3000000,
    },
    {
      id: 71,
      name: "Project Euler",
      url: "projecteuler.net/profile/",
      total_users: 1000000,
    },
    {
      id: 72,
      name: "Khan Academy",
      url: "khanacademy.org/profile/",
      total_users: 8000000,
    },
    {
      id: 73,
      name: "The Odin Project",
      url: "theodinproject.com/users/",
      total_users: 500000,
    },
    {
      id: 74,
      name: "Scrimba",
      url: "scrimba.com/user/",
      total_users: 1000000,
    },
    {
      id: 75,
      name: "TryHackMe",
      url: "tryhackme.com/p/",
      total_users: 2000000,
    },
    {
      id: 76,
      name: "Hack The Box",
      url: "hackthebox.com/u/",
      total_users: 1000000,
    },
    {
      id: 77,
      name: "Exploit Database",
      url: "exploit-db.com/author/",
      total_users: 500000,
    },
    {
      id: 78,
      name: "OpenAI Forum",
      url: "community.openai.com/u/",
      total_users: 1000000,
    },
    {
      id: 79,
      name: "MidJourney Forum",
      url: "community.midjourney.com/u/",
      total_users: 500000,
    },
    {
      id: 80,
      name: "Notion",
      url: "notion.so/@",
      total_users: 3000000,
    },
    {
      id: 81,
      name: "Trello",
      url: "trello.com/",
      total_users: 5000000,
    },
    {
      id: 82,
      name: "Asana",
      url: "asana.com/0/",
      total_users: 4000000,
    },
    { id: 83, name: "Jira", url: "jira.com/", total_users: 3000000 },
    {
      id: 84,
      name: "Todoist",
      url: "todoist.com/app/@",
      total_users: 2000000,
    },
    {
      id: 85,
      name: "Evernote",
      url: "evernote.com/u/",
      total_users: 2000000,
    },
    {
      id: 86,
      name: "Roam Research",
      url: "roamresearch.com/#/app/",
      total_users: 1000000,
    },
    {
      id: 87,
      name: "Obsidian Publish",
      url: "publish.obsidian.md/@",
      total_users: 500000,
    },
    {
      id: 88,
      name: "TiddlyWiki",
      url: "tiddlyhost.com/#/",
      total_users: 300000,
    },
    {
      id: 89,
      name: "Fandom Wiki",
      url: "fandom.com/wiki/User:",
      total_users: 5000000,
    },
    {
      id: 90,
      name: "WikiTree",
      url: "wikitree.com/wiki/",
      total_users: 2000000,
    },
    {
      id: 91,
      name: "Wikia",
      url: "wikia.com/wiki/User:",
      total_users: 3000000,
    },
    {
      id: 92,
      name: "Miraheze",
      url: "miraheze.org/wiki/User:",
      total_users: 1000000,
    },
    {
      id: 93,
      name: "Neocities",
      url: ".neocities.org",
      total_users: 500000,
    },
    { id: 94, name: "Carrd", url: ".carrd.co", total_users: 700000 },
    {
      id: 95,
      name: "Webflow",
      url: "webflow.com/@",
      total_users: 600000,
    },
    {
      id: 96,
      name: "Weebly",
      url: ".weebly.com",
      total_users: 1000000,
    },
    { id: 97, name: "Wix", url: ".wixsite.com", total_users: 2000000 },
    {
      id: 98,
      name: "Squarespace",
      url: ".squarespace.com",
      total_users: 1500000,
    },
    {
      id: 99,
      name: "Strikingly",
      url: ".mystrikingly.com",
      total_users: 500000,
    },
    {
      id: 100,
      name: "Yola",
      url: ".yolasite.com",
      total_users: 300000,
    },
    {
      id: 101,
      name: "GitHub Pages",
      url: ".github.io",
      total_users: 5000000,
    },
    {
      id: 102,
      name: "SourceForge",
      url: "sourceforge.net/u/",
      total_users: 2000000,
    },
    {
      id: 103,
      name: "CPAN",
      url: "metacpan.org/author/",
      total_users: 500000,
    },
    {
      id: 104,
      name: "Bandcamp",
      url: "bandcamp.com/",
      total_users: 1000000,
    },
    {
      id: 105,
      name: "Discogs",
      url: "discogs.com/user/",
      total_users: 800000,
    },
    {
      id: 106,
      name: "MusicBrainz",
      url: "musicbrainz.org/user/",
      total_users: 500000,
    },
    {
      id: 107,
      name: "Mixcloud",
      url: "mixcloud.com/",
      total_users: 1000000,
    },
    {
      id: 108,
      name: "SoundCloud",
      url: "soundcloud.com/",
      total_users: 76000000,
    },
    {
      id: 109,
      name: "Audiomack",
      url: "audiomack.com/",
      total_users: 5000000,
    },
    { id: 110, name: "BAND", url: "band.us/@", total_users: 2000000 },
    {
      id: 111,
      name: "Letterboxd",
      url: "letterboxd.com/",
      total_users: 3000000,
    },
    {
      id: 112,
      name: "Vimeo",
      url: "vimeo.com/user/",
      total_users: 20000000,
    },
    {
      id: 113,
      name: "Dailymotion",
      url: "dailymotion.com/user/",
      total_users: 5000000,
    },
    {
      id: 114,
      name: "Twitch",
      url: "twitch.tv/",
      total_users: 100000000,
    },
    {
      id: 115,
      name: "YouTube",
      url: "youtube.com/c/",
      total_users: 2000000000,
    },
    {
      id: 116,
      name: "Snapchat",
      url: "snapchat.com/add/",
      total_users: 500000000,
    },
    {
      id: 117,
      name: "Reddit",
      url: "reddit.com/user/",
      total_users: 430000000,
    },
    {
      id: 118,
      name: "Pinterest",
      url: "pinterest.com/",
      total_users: 450000000,
    },
    {
      id: 119,
      name: "Flickr",
      url: "flickr.com/photos/",
      total_users: 100000000,
    },
    { id: 120, name: "Mix", url: "mix.com/", total_users: 10000000 },
    {
      id: 121,
      name: "500px",
      url: "500px.com/",
      total_users: 20000000,
    },
    {
      id: 122,
      name: "GitLab",
      url: "gitlab.com/",
      total_users: 30000000,
    },
    {
      id: 123,
      name: "Bitbucket",
      url: "bitbucket.org/",
      total_users: 10000000,
    },
    {
      id: 124,
      name: "Xing",
      url: "xing.com/profile/",
      total_users: 17000000,
    },
    {
      id: 125,
      name: "Slack",
      url: "slack.com/team/",
      total_users: 15000000,
    },
    {
      id: 126,
      name: "Microsoft Teams",
      url: "teams.microsoft.com/l/team/",
      total_users: 270000000,
    },
    {
      id: 127,
      name: "Salesforce",
      url: "salesforce.com/user/",
      total_users: 1500000,
    },
    {
      id: 128,
      name: "HubSpot",
      url: "hubspot.com/user/",
      total_users: 6000000,
    },
    { id: 129, name: "Zoho", url: "zoho.com/", total_users: 5000000 },
    {
      id: 130,
      name: "Mailchimp",
      url: "mailchimp.com/",
      total_users: 12000000,
    },
    { id: 131, name: "Asana", url: "asana.com/", total_users: 7000000 },
    {
      id: 132,
      name: "Dropbox",
      url: "dropbox.com/",
      total_users: 500000000,
    },
    { id: 133, name: "Box", url: "box.com/", total_users: 10000000 },
    {
      id: 134,
      name: "Evernote",
      url: "evernote.com/",
      total_users: 30000000,
    },
    {
      id: 135,
      name: "Trello",
      url: "trello.com/",
      total_users: 50000000,
    },
    {
      id: 136,
      name: "Notion",
      url: "notion.so/",
      total_users: 20000000,
    },
    {
      id: 137,
      name: "Google Drive",
      url: "drive.google.com/",
      total_users: 1000000000,
    },
    {
      id: 138,
      name: "WeTransfer",
      url: "wetransfer.com/",
      total_users: 20000000,
    },
    { id: 139, name: "Toggl", url: "toggl.com/", total_users: 5000000 },
    {
      id: 140,
      name: "FreshBooks",
      url: "freshbooks.com/",
      total_users: 2000000,
    },
    {
      id: 141,
      name: "QuickBooks",
      url: "quickbooks.intuit.com/",
      total_users: 10000000,
    },
    {
      id: 142,
      name: "Wave",
      url: "waveapps.com/",
      total_users: 10000000,
    },
    { id: 143, name: "Mint", url: "mint.com/", total_users: 20000000 },
    {
      id: 144,
      name: "Stripe",
      url: "stripe.com/",
      total_users: 50000000,
    },
    {
      id: 145,
      name: "PayPal",
      url: "paypal.com/",
      total_users: 350000000,
    },
    {
      id: 146,
      name: "Square",
      url: "square.com/",
      total_users: 3000000,
    },
    {
      id: 147,
      name: "Venmo",
      url: "venmo.com/",
      total_users: 80000000,
    },
    {
      id: 148,
      name: "Cash App",
      url: "cash.app/$",
      total_users: 30000000,
    },
    {
      id: 149,
      name: "Apple Pay",
      url: "apple.com/",
      total_users: 1000000000,
    },
    {
      id: 150,
      name: "Google Pay",
      url: "pay.google.com/",
      total_users: 200000000,
    },
    {
      id: 151,
      name: "Klarna",
      url: "klarna.com/",
      total_users: 5000000,
    },
    {
      id: 152,
      name: "Shopify",
      url: "shopify.com/",
      total_users: 20000000,
    },
    {
      id: 153,
      name: "BigCommerce",
      url: "bigcommerce.com/",
      total_users: 2000000,
    },
    {
      id: 154,
      name: "WooCommerce",
      url: "woocommerce.com/",
      total_users: 10000000,
    },
    {
      id: 155,
      name: "Etsy",
      url: "etsy.com/shop/",
      total_users: 45000000,
    },
    {
      id: 156,
      name: "eBay",
      url: "ebay.com/usr/",
      total_users: 170000000,
    },
    {
      id: 157,
      name: "Amazon",
      url: "amazon.com/",
      total_users: 300000000,
    },
    {
      id: 158,
      name: "AliExpress",
      url: "aliexpress.com/store/",
      total_users: 100000000,
    },
    {
      id: 159,
      name: "Rakuten",
      url: "rakuten.com/shop/",
      total_users: 50000000,
    },
    {
      id: 160,
      name: "Walmart",
      url: "walmart.com/",
      total_users: 150000000,
    },
    {
      id: 161,
      name: "Target",
      url: "target.com/",
      total_users: 50000000,
    },
    {
      id: 162,
      name: "Macy's",
      url: "macys.com/",
      total_users: 10000000,
    },
    {
      id: 163,
      name: "Best Buy",
      url: "bestbuy.com/profile/",
      total_users: 15000000,
    },
    {
      id: 164,
      name: "Costco",
      url: "costco.com/",
      total_users: 10000000,
    },
    {
      id: 165,
      name: "Home Depot",
      url: "homedepot.com/profile/",
      total_users: 20000000,
    },
    {
      id: 166,
      name: "Lowe's",
      url: "lowes.com/profile/",
      total_users: 10000000,
    },
    {
      id: 167,
      name: "Bed Bath & Beyond",
      url: "bedbathandbeyond.com/profile/",
      total_users: 5000000,
    },
    {
      id: 168,
      name: "Nordstrom",
      url: "nordstrom.com/",
      total_users: 20000000,
    },
    { id: 169, name: "Sears", url: "sears.com/", total_users: 5000000 },
    {
      id: 170,
      name: "Kroger",
      url: "kroger.com/",
      total_users: 20000000,
    },
    { id: 171, name: "CVS", url: "cvs.com/", total_users: 10000000 },
    {
      id: 172,
      name: "Walgreens",
      url: "walgreens.com/",
      total_users: 10000000,
    },
    {
      id: 173,
      name: "Sam's Club",
      url: "samsclub.com/",
      total_users: 5000000,
    },
    { id: 174, name: "Ikea", url: "ikea.com/", total_users: 20000000 },
    { id: 175, name: "Zara", url: "zara.com/", total_users: 50000000 },
    { id: 176, name: "H&M", url: "hm.com/", total_users: 20000000 },
    {
      id: 177,
      name: "Uniqlo",
      url: "uniqlo.com/",
      total_users: 20000000,
    },
    { id: 178, name: "Nike", url: "nike.com/", total_users: 100000000 },
    {
      id: 179,
      name: "Adidas",
      url: "adidas.com/",
      total_users: 50000000,
    },
    {
      id: 180,
      name: "Under Armour",
      url: "underarmour.com/",
      total_users: 5000000,
    },
    {
      id: 181,
      name: "Reebok",
      url: "reebok.com/",
      total_users: 10000000,
    },
    { id: 182, name: "Puma", url: "puma.com/", total_users: 5000000 },
    {
      id: 183,
      name: "Converse",
      url: "converse.com/",
      total_users: 10000000,
    },
    {
      id: 184,
      name: "New Balance",
      url: "newbalance.com/",
      total_users: 10000000,
    },
    { id: 185, name: "Vans", url: "vans.com/", total_users: 20000000 },
    {
      id: 186,
      name: "Skechers",
      url: "skechers.com/",
      total_users: 10000000,
    },
    { id: 187, name: "Crocs", url: "crocs.com/", total_users: 5000000 },
    {
      id: 188,
      name: "Dr. Martens",
      url: "drmartens.com/",
      total_users: 5000000,
    },
    {
      id: 189,
      name: "Timberland",
      url: "timberland.com/",
      total_users: 10000000,
    },
    { id: 190, name: "Ugg", url: "ugg.com/", total_users: 10000000 },
    {
      id: 191,
      name: "North Face",
      url: "thenorthface.com/",
      total_users: 5000000,
    },
    {
      id: 192,
      name: "Columbia Sportswear",
      url: "columbia.com/",
      total_users: 20000000,
    },
    {
      id: 193,
      name: "Patagonia",
      url: "patagonia.com/",
      total_users: 10000000,
    },
    {
      id: 194,
      name: "Arc'teryx",
      url: "arcteryx.com/",
      total_users: 5000000,
    },
    {
      id: 195,
      name: "Marmot",
      url: "marmot.com/",
      total_users: 3000000,
    },
    {
      id: 196,
      name: "Mountain Hardwear",
      url: "mountainhardwear.com/",
      total_users: 10000000,
    },
    {
      id: 197,
      name: "Helly Hansen",
      url: "hellyhansen.com/",
      total_users: 3000000,
    },
    {
      id: 198,
      name: "Spyder",
      url: "spyder.com/",
      total_users: 10000000,
    },
    {
      id: 199,
      name: "L.L.Bean",
      url: "llbean.com/",
      total_users: 15000000,
    },
  ];